/*
 * Moderne Software Architekturen - 5x5-Labyrinth-API
 * API für das 5x5-Labyrinth-Spiel mit RESTful Endpunkten von Sebastian Wolf Mart.Nr 6771635
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.BoardSizeDto;
import org.openapitools.client.model.PositionDto;
import org.openapitools.client.model.WallDto;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BoardDto
 */
class BoardDtoTest {
    private final BoardDto model = new BoardDto();

    /**
     * Model tests for BoardDto
     */
    @Test
    void testBoardDto() {
        // TODO: test BoardDto
    }

    /**
     * Test the property 'size'
     */
    @Test
    void sizeTest() {
        // TODO: test size
    }

    /**
     * Test the property 'playerPosition'
     */
    @Test
    void playerPositionTest() {
        // TODO: test playerPosition
    }

    /**
     * Test the property 'goal'
     */
    @Test
    void goalTest() {
        // TODO: test goal
    }

    /**
     * Test the property 'walls'
     */
    @Test
    void wallsTest() {
        // TODO: test walls
    }

    /**
     * Test the property 'visited'
     */
    @Test
    void visitedTest() {
        // TODO: test visited
    }

}
